
# Created by: FAVERO FLEXXX


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_calc_flx(object):
    def setupUi(self, calc_flx):
        calc_flx.setObjectName("calc_flx")
        calc_flx.resize(890, 690)
        calc_flx.setStyleSheet("background-color: #d9ad7c;\n"
"color: #fff2df;\n"
"font-family:Arial;\n"
"font-size:15px;\n"
"font-weight:bold;\n"
"")
        self.line = QtWidgets.QFrame(calc_flx)
        self.line.setGeometry(QtCore.QRect(370, -30, 3, 800))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.tabWidget = QtWidgets.QTabWidget(calc_flx)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 301, 211))
        self.tabWidget.setStyleSheet("color: #674d3c;\n"
"background-color: #a2836e;")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.IR = QtWidgets.QWidget()
        self.IR.setObjectName("IR")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.IR)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 261, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setStyleSheet("color: rgb(255, 242, 223);\n"
"background-color: #a2836e;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.induttanza = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.induttanza.setStyleSheet("border: 2px solid #fff2df;\n"
"border-radius:6px;")
        self.induttanza.setObjectName("induttanza")
        self.horizontalLayout.addWidget(self.induttanza)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setStyleSheet("background-color: #a2836e;\n"
"color: rgb(255, 242, 223);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.resistenza_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.resistenza_1.setStyleSheet("border: 2px solid #fff2df;\n"
"border-radius:6px;")
        self.resistenza_1.setObjectName("resistenza_1")
        self.horizontalLayout_2.addWidget(self.resistenza_1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_7 = QtWidgets.QLabel(self.IR)
        self.label_7.setGeometry(QtCore.QRect(-10, -30, 311, 241))
        self.label_7.setStyleSheet("background-color: #d9ad7c;\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.IR)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 281, 161))
        self.label_8.setStyleSheet("background-color: #a2836e;\n"
"border: 2px solid #fff2df;\n"
"border-radius:15px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_7.raise_()
        self.label_8.raise_()
        self.verticalLayoutWidget.raise_()
        self.tabWidget.addTab(self.IR, "")
        self.RC = QtWidgets.QWidget()
        self.RC.setObjectName("RC")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.RC)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 261, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setStyleSheet("color: rgb(255, 242, 223);\n"
"background-color: #a2836e;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.resistenza_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.resistenza_2.setStyleSheet("border: 2px solid #fff2df;\n"
"border-radius:6px;")
        self.resistenza_2.setObjectName("resistenza_2")
        self.horizontalLayout_3.addWidget(self.resistenza_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setStyleSheet("background-color: #a2836e;\n"
"color: rgb(255, 242, 223);\n"
"font-size:14px;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.condensatore = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.condensatore.setStyleSheet("border: 2px solid #fff2df;\n"
"border-radius:6px;")
        self.condensatore.setObjectName("condensatore")
        self.horizontalLayout_4.addWidget(self.condensatore)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_9 = QtWidgets.QLabel(self.RC)
        self.label_9.setGeometry(QtCore.QRect(-10, -10, 321, 221))
        self.label_9.setStyleSheet("background-color: #d9ad7c;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.RC)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 281, 161))
        self.label_10.setStyleSheet("background-color: #a2836e;\n"
"border: 2px solid #fff2df;\n"
"border-radius:15px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_9.raise_()
        self.label_10.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.tabWidget.addTab(self.RC, "")
        self.label_6 = QtWidgets.QLabel(calc_flx)
        self.label_6.setGeometry(QtCore.QRect(-30, -40, 951, 821))
        self.label_6.setStyleSheet("background-color: #674d3c;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(calc_flx)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 331, 241))
        self.label_11.setStyleSheet("background-color: rgb(162, 131, 110);\n"
"border-radius: 20px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(calc_flx)
        self.label_12.setGeometry(QtCore.QRect(20, 260, 331, 301))
        self.label_12.setStyleSheet("background-color: rgb(162, 131, 110);\n"
"border-radius: 20px;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(calc_flx)
        self.label_13.setGeometry(QtCore.QRect(30, 270, 311, 281))
        self.label_13.setStyleSheet("background-color: #d9ad7c;\n"
"border-radius: 10px")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(calc_flx)
        self.label_14.setGeometry(QtCore.QRect(390, 490, 481, 111))
        self.label_14.setStyleSheet("background-color: rgb(162, 131, 110);\n"
"border-radius: 20px;")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(calc_flx)
        self.label_15.setGeometry(QtCore.QRect(410, 500, 441, 91))
        self.label_15.setStyleSheet("background-color: #d9ad7c;\n"
"border-radius: 10px")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(calc_flx)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(420, 507, 411, 81))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.anteprimaGrafico = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.anteprimaGrafico.setStyleSheet("background-color: #674d3c;\n"
"")
        self.anteprimaGrafico.setObjectName("anteprimaGrafico")
        self.verticalLayout_3.addWidget(self.anteprimaGrafico)
        self.salvataggio = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.salvataggio.setStyleSheet("background-color: #674d3c;")
        self.salvataggio.setObjectName("salvataggio")
        self.verticalLayout_3.addWidget(self.salvataggio)
        self.label_16 = QtWidgets.QLabel(calc_flx)
        self.label_16.setGeometry(QtCore.QRect(390, 610, 481, 61))
        self.label_16.setStyleSheet("background-color: rgb(162, 131, 110);\n"
"border-radius: 20px;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(calc_flx)
        self.label_17.setGeometry(QtCore.QRect(410, 620, 441, 41))
        self.label_17.setStyleSheet("background-color: #d9ad7c;\n"
"border-radius: 10px")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.cartellaSalvataggi = QtWidgets.QPushButton(calc_flx)
        self.cartellaSalvataggi.setGeometry(QtCore.QRect(420, 630, 421, 24))
        self.cartellaSalvataggi.setStyleSheet("background-color: #674d3c;")
        self.cartellaSalvataggi.setObjectName("cartellaSalvataggi")
        self.frame = QtWidgets.QFrame(calc_flx)
        self.frame.setGeometry(QtCore.QRect(390, 10, 481, 471))
        self.frame.setStyleSheet("background-color: rgb(162, 131, 110);\n"
"border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_32 = QtWidgets.QLabel(calc_flx)
        self.label_32.setGeometry(QtCore.QRect(20, 570, 331, 101))
        self.label_32.setStyleSheet("background-color: rgb(162, 131, 110);\n"
"border-radius: 20px;")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(calc_flx)
        self.label_33.setGeometry(QtCore.QRect(30, 580, 311, 81))
        self.label_33.setStyleSheet("background-color: #d9ad7c;\n"
"border-radius: 10px")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.horizontalLayoutWidget = QtWidgets.QWidget(calc_flx)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 590, 291, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_34.setMinimumSize(QtCore.QSize(0, 0))
        self.label_34.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_34.setAutoFillBackground(False)
        self.label_34.setStyleSheet("background-color: #d9ad7c;")
        self.label_34.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_6.addWidget(self.label_34)
        self.tempo_ripetizioni = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.tempo_ripetizioni.setStyleSheet("border: 2px solid #fff2df;\n"
"background-color: rgb(162, 131, 110);\n"
"border-radius:6px;")
        self.tempo_ripetizioni.setObjectName("tempo_ripetizioni")
        self.horizontalLayout_6.addWidget(self.tempo_ripetizioni)
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_35.setMinimumSize(QtCore.QSize(0, 0))
        self.label_35.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_35.setAutoFillBackground(False)
        self.label_35.setStyleSheet("background-color: #d9ad7c;")
        self.label_35.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_6.addWidget(self.label_35)
        self.layoutWidget = QtWidgets.QWidget(calc_flx)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 320, 289, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.box_quadra = QtWidgets.QCheckBox(self.layoutWidget)
        self.box_quadra.setText("")
        self.box_quadra.setObjectName("box_quadra")
        self.horizontalLayout_7.addWidget(self.box_quadra)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(120, 0))
        self.label_20.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_20.setAutoFillBackground(False)
        self.label_20.setStyleSheet("background-color: #d9ad7c;")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.Vi_quad1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Vi_quad1.setStyleSheet("border: 2px solid #fff2df;\n"
"background-color: rgb(162, 131, 110);\n"
"border-radius:6px;")
        self.Vi_quad1.setObjectName("Vi_quad1")
        self.horizontalLayout_7.addWidget(self.Vi_quad1)
        self.Vi_quad2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Vi_quad2.setStyleSheet("border: 2px solid #fff2df;\n"
"background-color: rgb(162, 131, 110);\n"
"border-radius:6px;")
        self.Vi_quad2.setObjectName("Vi_quad2")
        self.horizontalLayout_7.addWidget(self.Vi_quad2)
        self.layoutWidget_2 = QtWidgets.QWidget(calc_flx)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 360, 289, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.box_rampa = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.box_rampa.setText("")
        self.box_rampa.setObjectName("box_rampa")
        self.horizontalLayout_8.addWidget(self.box_rampa)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setMinimumSize(QtCore.QSize(120, 0))
        self.label_21.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_21.setAutoFillBackground(False)
        self.label_21.setStyleSheet("background-color: #d9ad7c;")
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.layoutWidget_3 = QtWidgets.QWidget(calc_flx)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 400, 289, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.box_parabola = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.box_parabola.setText("")
        self.box_parabola.setObjectName("box_parabola")
        self.horizontalLayout_9.addWidget(self.box_parabola)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_22.setMinimumSize(QtCore.QSize(120, 0))
        self.label_22.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_22.setAutoFillBackground(False)
        self.label_22.setStyleSheet("background-color: #d9ad7c;")
        self.label_22.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_9.addWidget(self.label_22)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_24.setMinimumSize(QtCore.QSize(120, 0))
        self.label_24.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_24.setAutoFillBackground(False)
        self.label_24.setStyleSheet("background-color: #d9ad7c;")
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_9.addWidget(self.label_24)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.layoutWidget_4 = QtWidgets.QWidget(calc_flx)
        self.layoutWidget_4.setGeometry(QtCore.QRect(40, 440, 289, 31))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.box_sinusoide = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.box_sinusoide.setText("")
        self.box_sinusoide.setObjectName("box_sinusoide")
        self.horizontalLayout_11.addWidget(self.box_sinusoide)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_23.setMinimumSize(QtCore.QSize(0, 0))
        self.label_23.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_23.setAutoFillBackground(False)
        self.label_23.setStyleSheet("background-color: #d9ad7c;")
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.const_sinusoide_1 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.const_sinusoide_1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.const_sinusoide_1.setStyleSheet("border: 2px solid #fff2df;\n"
"background-color: rgb(162, 131, 110);\n"
"border-radius:6px;")
        self.const_sinusoide_1.setObjectName("const_sinusoide_1")
        self.horizontalLayout_11.addWidget(self.const_sinusoide_1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_25.setMinimumSize(QtCore.QSize(0, 0))
        self.label_25.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_25.setAutoFillBackground(False)
        self.label_25.setStyleSheet("background-color: #d9ad7c;")
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_11.addWidget(self.label_25)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_26.setMinimumSize(QtCore.QSize(0, 0))
        self.label_26.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_26.setAutoFillBackground(False)
        self.label_26.setStyleSheet("background-color: #d9ad7c;")
        self.label_26.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_11.addWidget(self.label_26)
        self.omega_1 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.omega_1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.omega_1.setStyleSheet("border: 2px solid #fff2df;\n"
"background-color: rgb(162, 131, 110);\n"
"border-radius:6px;")
        self.omega_1.setObjectName("omega_1")
        self.horizontalLayout_11.addWidget(self.omega_1)
        self.layoutWidget_5 = QtWidgets.QWidget(calc_flx)
        self.layoutWidget_5.setGeometry(QtCore.QRect(40, 480, 289, 31))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.box_sinusoide_2 = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.box_sinusoide_2.setText("")
        self.box_sinusoide_2.setObjectName("box_sinusoide_2")
        self.horizontalLayout_12.addWidget(self.box_sinusoide_2)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_27.setMinimumSize(QtCore.QSize(0, 0))
        self.label_27.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_27.setAutoFillBackground(False)
        self.label_27.setStyleSheet("background-color: #d9ad7c;")
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_12.addWidget(self.label_27)
        self.const_sinusoide_2 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.const_sinusoide_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.const_sinusoide_2.setStyleSheet("border: 2px solid #fff2df;\n"
"background-color: rgb(162, 131, 110);\n"
"border-radius:6px;")
        self.const_sinusoide_2.setObjectName("const_sinusoide_2")
        self.horizontalLayout_12.addWidget(self.const_sinusoide_2)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_28.setMinimumSize(QtCore.QSize(0, 0))
        self.label_28.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_28.setAutoFillBackground(False)
        self.label_28.setStyleSheet("background-color: #d9ad7c;")
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_12.addWidget(self.label_28)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_29.setMinimumSize(QtCore.QSize(0, 0))
        self.label_29.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_29.setAutoFillBackground(False)
        self.label_29.setStyleSheet("background-color: #d9ad7c;")
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_12.addWidget(self.label_29)
        self.omega_2 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.omega_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.omega_2.setStyleSheet("border: 2px solid #fff2df;\n"
"background-color: rgb(162, 131, 110);\n"
"border-radius:6px;")
        self.omega_2.setObjectName("omega_2")
        self.horizontalLayout_12.addWidget(self.omega_2)
        self.layoutWidget_6 = QtWidgets.QWidget(calc_flx)
        self.layoutWidget_6.setGeometry(QtCore.QRect(40, 510, 289, 31))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem4 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_30.setMinimumSize(QtCore.QSize(0, 0))
        self.label_30.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_30.setAutoFillBackground(False)
        self.label_30.setStyleSheet("background-color: #d9ad7c;")
        self.label_30.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_13.addWidget(self.label_30)
        self.disturbo = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.disturbo.setStyleSheet("border: 2px solid #fff2df;\n"
"background-color: rgb(162, 131, 110);\n"
"border-radius:6px;")
        self.disturbo.setObjectName("disturbo")
        self.horizontalLayout_13.addWidget(self.disturbo)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_31.setMinimumSize(QtCore.QSize(0, 0))
        self.label_31.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_31.setAutoFillBackground(False)
        self.label_31.setStyleSheet("background-color: #d9ad7c;")
        self.label_31.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_13.addWidget(self.label_31)
        self.layoutWidget_7 = QtWidgets.QWidget(calc_flx)
        self.layoutWidget_7.setGeometry(QtCore.QRect(40, 280, 289, 33))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.box_costante = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.box_costante.setText("")
        self.box_costante.setObjectName("box_costante")
        self.horizontalLayout_14.addWidget(self.box_costante)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_36.setMinimumSize(QtCore.QSize(120, 0))
        self.label_36.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_36.setAutoFillBackground(False)
        self.label_36.setStyleSheet("background-color: #d9ad7c;")
        self.label_36.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_14.addWidget(self.label_36)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.Vi_const = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.Vi_const.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Vi_const.setStyleSheet("border: 2px solid #fff2df;\n"
"background-color: rgb(162, 131, 110);\n"
"border-radius:6px;")
        self.Vi_const.setObjectName("Vi_const")
        self.horizontalLayout_14.addWidget(self.Vi_const)
        self.autoset = QtWidgets.QPushButton(calc_flx)
        self.autoset.setGeometry(QtCore.QRect(40, 630, 291, 21))
        self.autoset.setStyleSheet("background-color: #674d3c;\n"
"")
        self.autoset.setObjectName("autoset")
        self.label_6.raise_()
        self.label_32.raise_()
        self.label_33.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_11.raise_()
        self.line.raise_()
        self.tabWidget.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.cartellaSalvataggi.raise_()
        self.frame.raise_()
        self.horizontalLayoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget_2.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_4.raise_()
        self.layoutWidget_5.raise_()
        self.layoutWidget_6.raise_()
        self.layoutWidget_7.raise_()
        self.autoset.raise_()

        self.retranslateUi(calc_flx)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(calc_flx)

    def retranslateUi(self, calc_flx):
        _translate = QtCore.QCoreApplication.translate
        calc_flx.setWindowTitle(_translate("calc_flx", "calc_flx"))
        self.label.setText(_translate("calc_flx", "INDUTTANZA"))
        self.label_2.setText(_translate("calc_flx", "RESISTENZA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IR), _translate("calc_flx", "I/R"))
        self.label_3.setText(_translate("calc_flx", "RESISTENZA"))
        self.label_4.setText(_translate("calc_flx", "CONDENSATORE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RC), _translate("calc_flx", "RC"))
        self.anteprimaGrafico.setText(_translate("calc_flx", " ANTEPRIMA GRAFICO"))
        self.salvataggio.setText(_translate("calc_flx", "SALVATAGGIO DATI"))
        self.cartellaSalvataggi.setText(_translate("calc_flx", "CARTELLA SALVATAGGI"))
        self.label_34.setText(_translate("calc_flx", "UN CAMPIONE OGNI"))
        self.label_35.setText(_translate("calc_flx", "SEC"))
        self.label_20.setText(_translate("calc_flx", "Vi(t) [QUADRA] = "))
        self.label_21.setText(_translate("calc_flx", "Vi(t) [RAMPA] = tempo"))
        self.label_22.setText(_translate("calc_flx", "Vi(t) [Parabola] ="))
        self.label_24.setText(_translate("calc_flx", "1/2*T^2"))
        self.label_23.setText(_translate("calc_flx", "Vi(t)="))
        self.label_25.setText(_translate("calc_flx", "*sen(wt)"))
        self.label_26.setText(_translate("calc_flx", "F="))
        self.label_27.setText(_translate("calc_flx", "Vi(t)="))
        self.label_28.setText(_translate("calc_flx", "*sen(wt)"))
        self.label_29.setText(_translate("calc_flx", "F="))
        self.label_30.setText(_translate("calc_flx", "+"))
        self.label_31.setText(_translate("calc_flx", "*sen(w1000t)"))
        self.label_36.setText(_translate("calc_flx", "Vi(t) [COSTANTE] ="))
        self.autoset.setText(_translate("calc_flx", "AUTOSET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calc_flx = QtWidgets.QWidget()
    ui = Ui_calc_flx()
    ui.setupUi(calc_flx)
    calc_flx.show()
    sys.exit(app.exec())
